2023-05-27 03:00:38,451 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:38,452 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,454 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:38,454 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,455 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:38,455 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,456 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:38,457 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,458 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:38,458 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,458 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:38,458 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,459 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:38,460 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,460 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:38,460 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,461 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:38,461 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,462 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:38,462 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,463 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:38,463 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:38,463 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:38,464 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,397 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:39,397 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,398 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:39,398 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,399 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:39,399 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,400 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:39,401 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,401 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:39,401 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,402 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:39,402 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,402 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:39,403 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,403 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:39,403 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,404 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:39,404 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,404 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:39,405 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,405 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:39,405 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,406 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:39,406 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,406 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:39,406 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,407 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:39,407 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,407 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:39,408 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,408 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.10, port:9003)} : Client has an error! 
2023-05-27 03:00:39,409 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=6, internalEndPoint=TEndPoint(ip:172.20.0.10, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,409 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:39,409 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:39,409 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.11, port:9003)} : Client has an error! 
2023-05-27 03:00:39,410 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=7, internalEndPoint=TEndPoint(ip:172.20.0.11, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,819 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:40,819 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,820 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:40,820 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,842 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:40,842 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,843 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:40,843 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,844 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:40,844 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,844 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:40,844 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,845 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:40,845 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,845 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:40,846 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,846 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:40,846 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,847 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:40,847 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,851 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:40,851 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:40,851 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.12, port:9003)} : Client has an error! 
2023-05-27 03:00:40,852 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=8, internalEndPoint=TEndPoint(ip:172.20.0.12, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,967 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.14, port:9003)} : Client has an error! 
2023-05-27 03:00:41,967 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=10, internalEndPoint=TEndPoint(ip:172.20.0.14, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,967 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:41,967 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,968 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.15, port:9003)} : Client has an error! 
2023-05-27 03:00:41,968 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=11, internalEndPoint=TEndPoint(ip:172.20.0.15, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,989 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:41,990 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,990 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.15, port:9003)} : Client has an error! 
2023-05-27 03:00:41,990 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=11, internalEndPoint=TEndPoint(ip:172.20.0.15, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,991 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.14, port:9003)} : Client has an error! 
2023-05-27 03:00:41,991 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=10, internalEndPoint=TEndPoint(ip:172.20.0.14, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,992 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:41,992 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,992 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.14, port:9003)} : Client has an error! 
2023-05-27 03:00:41,992 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=10, internalEndPoint=TEndPoint(ip:172.20.0.14, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,993 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.15, port:9003)} : Client has an error! 
2023-05-27 03:00:41,993 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=11, internalEndPoint=TEndPoint(ip:172.20.0.15, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,993 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:41,994 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,994 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.14, port:9003)} : Client has an error! 
2023-05-27 03:00:41,994 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=10, internalEndPoint=TEndPoint(ip:172.20.0.14, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,995 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.15, port:9003)} : Client has an error! 
2023-05-27 03:00:41,995 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=11, internalEndPoint=TEndPoint(ip:172.20.0.15, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,996 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:41,996 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,996 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.14, port:9003)} : Client has an error! 
2023-05-27 03:00:41,996 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=10, internalEndPoint=TEndPoint(ip:172.20.0.14, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,997 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.15, port:9003)} : Client has an error! 
2023-05-27 03:00:41,997 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=11, internalEndPoint=TEndPoint(ip:172.20.0.15, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,997 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.13, port:9003)} : Client has an error! 
2023-05-27 03:00:41,998 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=9, internalEndPoint=TEndPoint(ip:172.20.0.13, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,998 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.14, port:9003)} : Client has an error! 
2023-05-27 03:00:41,998 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=10, internalEndPoint=TEndPoint(ip:172.20.0.14, port:9003)}, exception: Connection refused 
2023-05-27 03:00:41,998 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.AsyncDataNodeInternalServiceClient:112 - Unexpected exception occurs in AsyncDataNodeInternalServiceClient{TEndPoint(ip:172.20.0.15, port:9003)} : Client has an error! 
2023-05-27 03:00:41,999 [AsyncDataNodeInternalServiceClientPool-selector-77] ERROR o.a.i.c.c.a.h.r.AsyncTSStatusRPCHandler:78 - Failed to BROADCAST_LATEST_CONFIG_NODE_GROUP on DataNode: {id=11, internalEndPoint=TEndPoint(ip:172.20.0.15, port:9003)}, exception: Connection refused 
2023-05-27 03:01:23,746 [pool-11-IoTDB-ConfigNodeRPC-Processor-23] ERROR o.a.t.s.TThreadPoolServer$WorkerProcess:258 - Thrift Error occurred during processing of message. 
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:178)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
	at org.apache.iotdb.rpc.TElasticFramedTransport.readFrame(TElasticFramedTransport.java:112)
	at org.apache.iotdb.rpc.TElasticFramedTransport.read(TElasticFramedTransport.java:107)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:463)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:361)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:244)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:176)
	... 12 common frames omitted
